### ISSUE TITLE
to clarify: the fork is missing all modules

### ISSUE THREAD

**Issue by blshkv** [opsdisk/metagoofil#7]
It seems like you are trying to continue the original work and this would be really cool. However, your "fork" has much lesser code. it's 550kb (old) vs 15kb (new).

Could you clarify it please?

**Comment by opsdisk** [comment]
Hi @blshkv ...yeah, it just supports Google right now...since that's what I mostly used it for and I wanted to keep it simple.  laramies (https://github.com/laramies/metagoofil) is larger in size because he has the additional code for the other modules, wrote his own google search library (as opposed to using the `googlesearch` one), and has a metadata search functionality and library.

**Comment by blshkv** [comment]
ok, great. That explains it. I like your approach by using existing modules. Keep it going!
Please also tag a release version at some point
